export let mappb = [
    {
        startPlanet:0,
        endPlanet:6,
        fuelLimit:12,
        Planets:[
            {
                time:0,
                linkedPlanets:[
                    {
                        planetNumber:1,
                        useFuel:1
                    },
                    {
                        planetNumber:3,
                        useFuel:4
                    },
                ]
            },
            {
                time:4,
                linkedPlanets:[
                    {
                        planetNumber:3,
                        useFuel:2
                    },
                    {
                        planetNumber:2,
                        useFuel:2
                    },
                ]
            },
            {
                time:2,
                linkedPlanets:[
                    {
                        planetNumber:4,
                        useFuel:4
                    },
                    {
                        planetNumber:5,
                        useFuel:3
                    },
                ]
            },
            {
                time:1,
                linkedPlanets:[
                    {
                        planetNumber:5,
                        useFuel:3
                    }
                ]
            },
            {
                time:0,
                linkedPlanets:[
                    {
                        planetNumber:6,
                        useFuel:2
                    }
                ]
            },
            {
                time:3,
                linkedPlanets:[
                    {
                        planetNumber:6,
                        useFuel:6
                    }
                ]
            },
            {
                time:0,
                linkedPlanets:[]
            },
        ]
    },
];

