export let mappb = [
    {
        startPlanet:0,
        endPlanet:6,
        fuelLimit:12,
        mapNumber:0,
        Planets:[
            {
                time:0,
                linkedPlanets:[
                    {
                        planetNumber:1,
                        useFuel:1
                    },
                    {
                        planetNumber:3,
                        useFuel:4
                    },
                ]
            },
            {
                time:4,
                linkedPlanets:[
                    {
                        planetNumber:3,
                        useFuel:2
                    },
                    {
                        planetNumber:2,
                        useFuel:2
                    },
                ]
            },
            {
                time:2,
                linkedPlanets:[
                    {
                        planetNumber:4,
                        useFuel:4
                    },
                    {
                        planetNumber:5,
                        useFuel:3
                    },
                ]
            },
            {
                time:1,
                linkedPlanets:[
                    {
                        planetNumber:5,
                        useFuel:3
                    }
                ]
            },
            {
                time:0,
                linkedPlanets:[
                    {
                        planetNumber:6,
                        useFuel:2
                    }
                ]
            },
            {
                time:3,
                linkedPlanets:[
                    {
                        planetNumber:6,
                        useFuel:6
                    }
                ]
            },
            {
                time:0,
                linkedPlanets:[]
            },
        ]
    },
    {
        startPlanet:0,
        endPlanet:6,
        fuelLimit:7,
        mapNumber:1,
        Planets:[
            {
                time:0,
                linkedPlanets:[
                    {
                        planetNumber:1,
                        useFuel:1
                    },
                    {
                        planetNumber:5,
                        useFuel:2
                    },
                ]
            },
            {
                time:2,
                linkedPlanets:[
                    {
                        planetNumber:2,
                        useFuel:1
                    },
                    {
                        planetNumber:3,
                        useFuel:2
                    },
                ]
            },
            {
                time:2,
                linkedPlanets:[
                    {
                        planetNumber:6,
                        useFuel:2
                    },
                ]
            },
            {
                time:3,
                linkedPlanets:[
                    {
                        planetNumber:4,
                        useFuel:1
                    },
                    {
                        planetNumber:5,
                        useFuel:2
                    },
                    {
                        planetNumber:6,
                        useFuel:2
                    }
                ]
            },
            {
                time:2,
                linkedPlanets:[
                    {
                        planetNumber:5,
                        useFuel:1
                    }
                ]
            },
            {
                time:0,
                linkedPlanets:[
                    {
                        planetNumber:6,
                        useFuel:8
                    }
                ]
            },
            {
                time:0,
                linkedPlanets:[]
            },
        ]
    },
    {
        startPlanet:0,
        endPlanet:6,
        fuelLimit:9,
        mapNumber:2,
        Planets:[
            {
                time:0,
                linkedPlanets:[
                    {
                        planetNumber:1,
                        useFuel:4
                    },
                    {
                        planetNumber:2,
                        useFuel:3
                    },
                ]
            },
            {
                time:1,
                linkedPlanets:[
                    {
                        planetNumber:3,
                        useFuel:1
                    },
                    {
                        planetNumber:4,
                        useFuel:1
                    },
                ]
            },
            {
                time:2,
                linkedPlanets:[
                    {
                        planetNumber:5,
                        useFuel:2
                    },
                    {
                        planetNumber:6,
                        useFuel:8
                    },
                ]
            },
            {
                time:2,
                linkedPlanets:[
                    {
                        planetNumber:4,
                        useFuel:3
                    },
                    {
                        planetNumber:5,
                        useFuel:1
                    },
                    
                ]
            },
            {
                time:3,
                linkedPlanets:[
                    {
                        planetNumber:6,
                        useFuel:5
                    }
                ]
            },
            {
                time:2,
                linkedPlanets:[
                    {
                        planetNumber:6,
                        useFuel:2
                    }
                ]
            },
            {
                time:4,
                linkedPlanets:[]
            },
        ]
    },
    {
        startPlanet:0,
        endPlanet:14,
        fuelLimit:14,
        mapNumber:3,
        Planets:[
            {
                time:0,
                linkedPlanets:[
                    {
                        planetNumber:1,
                        useFuel:3
                    },
                    {
                        planetNumber:2,
                        useFuel:3
                    },
                    {
                        planetNumber:3,
                        useFuel:3
                    },
                    
                ]
            },
            {
                time:1,
                linkedPlanets:[
                    {
                        planetNumber:6,
                        useFuel:4
                    },
                    {
                        planetNumber:10,
                        useFuel:6
                    },
                ]
            },
            {
                time:0,
                linkedPlanets:[
                    {
                        planetNumber:6,
                        useFuel:4
                    },
                    
                ]
            },
            {
                time:3,
                linkedPlanets:[
                    {
                        planetNumber:4,
                        useFuel:1
                    },
                    {
                        planetNumber:5,
                        useFuel:3
                    },
                    
                ]
            },
            {
                time:2,
                linkedPlanets:[]
            },
            {
                time:4,
                linkedPlanets:[
                    {
                        planetNumber:7,
                        useFuel:2
                    },
                    {
                        planetNumber:6,
                        useFuel:4
                    },
                ]
            },
            {
                time:2,
                linkedPlanets:[
                    {
                        planetNumber:8,
                        useFuel:2
                    },
                    {
                        planetNumber:10,
                        useFuel:3
                    },
                ]
            },
            {
                time:2,
                linkedPlanets:[
                    {
                        planetNumber:8,
                        useFuel:2
                    },
                ]
            },
            {
                time:1,
                linkedPlanets:[
                    {
                        planetNumber:9,
                        useFuel:1
                    },
                    {
                        planetNumber:12,
                        useFuel:3
                    },
                ]
            },
            {
                time:0,
                linkedPlanets:[
                    {
                        planetNumber:11,
                        useFuel:2
                    },
                ]
            },
            {
                time:0,
                linkedPlanets:[
                    {
                        planetNumber:12,
                        useFuel:2
                    },
                ]
            },
            {
                time:1,
                linkedPlanets:[
                    {
                        planetNumber:12,
                        useFuel:5
                    },
                    {
                        planetNumber:14,
                        useFuel:3
                    },
                ]
            },
            {
                time:3,
                linkedPlanets:[
                    {
                    planetNumber:13,
                    useFuel:1
                    },
                ]
            },
            {
                time:2,
                linkedPlanets:[
                    {
                        planetNumber:14,
                        useFuel:2
                    },
                ]
            },
            {
                time:0,
                linkedPlanets:[]
            },
        ]
    },
    {
        startPlanet:0,
        endPlanet:14,
        fuelLimit:14,
        mapNumber:4,
        Planets:[
            {
                time:0,
                linkedPlanets:[
                    {
                        planetNumber:1,
                        useFuel:1
                    },
                    {
                        planetNumber:2,
                        useFuel:1
                    },
                    {
                        planetNumber:4,
                        useFuel:3
                    },
                ]
            },
            {
                time:2,
                linkedPlanets:[]
            },
            {
                time:3,
                linkedPlanets:[
                    {
                        planetNumber:4,
                        useFuel:1
                    },
                    {
                        planetNumber:5,
                        useFuel:1
                    },
                ]
            },
            {
                time:1,
                linkedPlanets:[
                    {
                        planetNumber:4,
                        useFuel:1
                    },
                    {
                        planetNumber:6,
                        useFuel:2
                    },
                    
                ]
            },
            {
                time:1,
                linkedPlanets:[
                    {
                        planetNumber:7,
                        useFuel:5
                    }
                ]
            },
            {
                time:4,
                linkedPlanets:[]
            },
            {
                time:5,
                linkedPlanets:[
                    {
                        planetNumber:8,
                        useFuel:4
                    },
                    {
                        planetNumber:9,
                        useFuel:3
                    },
                ]
            },
            {
                time:2,
                linkedPlanets:[
                    {
                        planetNumber:9,
                        useFuel:3
                    },
                ]
            },
            {
                time:2,
                linkedPlanets:[]
            },
            {
                time:0,
                linkedPlanets:[]
            },
        ]
    },
];

